version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tennis_book?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - APP_JWT_SECRET=your-secret-key-should-be-very-long-and-secure-in-production
      - APP_JWT_EXPIRATION=86400000
    depends_on:
      - db
    networks:
      - tennis-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tennis_book
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tennis-network

networks:
  tennis-network:
    driver: bridge

volumes:
  mysql-data: 